# Use postgres/example user/password credentials
version: "3.1"
services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
